import React from "react";
import { Stack } from "@chakra-ui/react";

const CGS = () => {

  return (
    <Stack>
      <h1>Conditions de Service pour les utilisateurs européens</h1>
      <p>
        En tant que consommateur, vous pouvez accéder à la plate-forme en ligne de résolution des litiges de la Commission européenne ici : https://ec.europa.eu/consumers/odr. Veuillez noter qu'Atypikhouse ne s'engage ni ne s'oblige à utiliser un dispositif alternatif de résolution des litiges afin de résoudre des litiges avec les consommateurs.
        L'article 24 des présentes Conditions contient une convention d'arbitrage et une clause de renonciation aux recours collectif qui s'appliquent à toute procédure engagée contre Atypikhouse aux États-Unis. Veuillez les lire attentivement.
        Merci d'utiliser Atypikhouse !
        Les présentes Conditions de Service pour les utilisateurs européens (les « Conditions ») sont un contrat juridique contraignant entre vous et Atypikhouse qui régit votre utilisation des sites web, applications et autres offres d'Atypikhouse (appelés collectivement, la « plate-forme Atypikhouse »). Lorsqu'ils sont utilisés dans ces conditions, les termes « Atypikhouse », « nous », « notre » et « nos » font référence à l'entité Atypikhouse mentionnée à l'annexe 1 avec laquelle vous concluez un contrat.
        La plate-forme Atypikhouse offre un espace en ligne permettant aux utilisateurs (« Membres ») de publier, d'offrir, de rechercher et de réserver des services. Les Membres qui publient et offrent des services sont des « Hôtes » et les membres qui recherchent, réservent ou utilisent des services sont des « Voyageurs ». Tout membre peut à la fois être « Hôtes » et  « Voyageurs » . Les Hôtes offrent des hébergements (« Hébergements »), des activités, des excursions et des événements (« Expériences »), ainsi qu'une variété de services de voyage et autres (collectivement, les « Services d'hôte », et chaque offre de service d'hôte, une « Annonce »). Vous devez créer un compte pour accéder et utiliser de nombreuses fonctionnalités de la plate-forme Atypikhouse. Vous devez également veiller à ce que les informations de votre compte demeurent exactes. En tant que fournisseur de la plate-forme Atypikhouse, Atypikhouse ne possède, ne contrôle, n'offre et ne gère ni les annonces ni les Services d'hôte. Atypikhouse n'est pas partie aux contrats conclus directement entre les Hôtes et les Voyageurs, et Atypikhouse n'est pas agent immobilier ni assureur, pas non plus organisateur ou détaillant de voyages organisés en vertu de la directive (UE) 2015/2302. Atypikhouse n'agit pas en qualité de mandataire d'un quelconque Membre.
        Nous appliquons d'autres Conditions et Politiques complémentaires à ces Conditions comme notre Politique de confidentialité, qui décrit notre collecte et utilisation des données personnelles.
        Si vous êtes un Hôte, vous êtes tenu de comprendre et de respecter l'ensemble des lois, règlements, réglementations et contrats avec des tiers qui s'appliquent à votre Annonce ou vos Services d'hôte.
      </p>

      <h2>Conditions relatives aux voyageurs</h2>
      <p>1. Notre mission.</p>
      <p>2. Recherche et réservation sur Atypikhouse.</p>
      <p>3. Annulations, problèmes de voyage, remboursements et modifications de réservation.</p>
      <p>4. Vos responsabilités.</p>

      <h2>Conditions relatives aux hôtes</h2>
      <p>      5. Accueil de voyageurs avec Atypikhouse.</p>
      <p>      6. Gestion de votre annonce.</p>
      <p>      7. Annulations, problèmes de voyage et modifications de réservation.</p>
      <p>      8. Taxes.</p>
      <h2>      Conditions d'application générale</h2>
      <p>      9. Commentaires</p>
      <p>      10. Contenu.</p>
      <p>      11. Frais.</p>
      <p>      12. Règles de la plate-forme Atypikhouse.</p>
      <p>      13. Résiliation, suspension et autres mesures.</p>
      <p>      14. Modification des présentes Conditions</p>
      <p>      15. Règlement des plaintes et des réclamations pour dommages.</p>
      <p>      16. Rôle d'Atypikhouse.</p>
      <p>      17. Comptes membres.</p>
      <p>      18. Exclusion de responsabilité.</p>
      <p>      19. Limitation de responsabilité.</p>
      <p>      20. Indemnisation.</p>
      <p>      21. Entités contractantes.</p>
      <p>      22. Droit applicable et juridiction.</p>
      <p>      23. Divers.</p>
      <p>      24. Résolution des litiges et convention d'arbitrage aux États-Unis.</p>

      <h2>      Conditions supplémentaires spécifiques aux hôtes professionnels</h2>
      <p>      25. Utilisateurs professionnels.</p>
      <p>      26. Résiliation, suspension et autres mesures.</p>
      <p>      27. Traitement des plaintes et médiation.</p>
      <p>      28. Accès aux données.</p>
      <p>      29. Canaux de distribution supplémentaires.</p>

      <h2>      Annexe 1 - Entités contractantes</h2>
      <h3>      Conditions relatives aux voyageurs</h3>
      <p>      1. Notre mission.</p>
      <p>      Notre mission est de construire un monde où chacun puisse se sentir chez soi, n'importe où. Des cabanes aux châteaux en passant par les cours de cuisine, parcourez des millions d'Annonces pour trouver celles qui correspondent à votre façon de voyager. Pour en savoir plus sur une Annonce, consultez la description et les photos, le profil de l'Hôte et les commentaires des Voyageurs. Si vous avez des questions, envoyez un message à l'Hôte.</p>
      <p>      2. Recherche et réservation sur Atypikhouse.</p>
      <p>      2.1 Recherche. Vous pouvez rechercher des Services d'hôte en utilisant la destination du voyage.</p>
      <p>      2.2 Réservation. Lorsque vous réservez une Annonce, vous acceptez de payer tous les frais relatifs à votre réservation, y compris le prix annoncé pour l'Annonce, les frais applicables tels que les frais de service d'Atypikhouse, les taxes et tout autre élément identifié lors de la commande (collectivement, le « Prix total »). Vous acceptez également qu'Atypikhouse puisse facturer et collecter, lors de la commande, toute caution identifiée. Lorsque vous recevez la confirmation de réservation, un contrat de services d'hôte (parfois appelé réservation, dans les présentes Conditions) est conclu directement entre vous et l'Hôte. Les conditions d'annulation et tous les autres règlements, normes, politiques ou exigences identifiés dans l'annonce ou lors de la commande font partie de votre contrat avec l'Hôte.</p>
      <p>      2.3 Réservations d'Hébergement. Une réservation d'Hébergement est une licence limitée pour entrer, occuper et utiliser l'Hébergement. L'Hôte se réserve le droit de réintégrer l'Hébergement pendant votre séjour, le cas échéant si : (i) cela est raisonnablement nécessaire, (ii) cela est autorisé en vertu de votre contrat avec l'Hôte, et (iii) cela est conforme au droit applicable. Si vous restez après l'heure de départ, l'Hôte a le droit de vous faire partir d'une manière conforme au droit applicable, y compris en vous imposant des sanctions raisonnables pour séjour indûment prolongé. Vous ne pouvez pas dépasser le nombre maximal autorisé de Voyageurs.</p>
      <p>      3. Annulations, problèmes de voyage, remboursements et modifications de réservation.</p>
      <p>      3.1 Annulations, problèmes de voyage et remboursements. En règle générale, si vous annulez une réservation, le montant qui vous est remboursé est déterminé par la règle suivante :</p>
      <p>      Annulation gratuite jusqu'à 24 heures avant l'arrivée (heure indiquée dans l'e-mail de confirmation).</p>
      <p>      Au-delà, annulez avant l'arrivée prévue et obtenez un remboursement intégral, moins la première nuit et les frais de service.</p>

      <p>      Mais, dans certaines situations, d'autres conditions sont prioritaires et déterminent le montant qui vous est remboursé. Si un événement indépendant de votre volonté vous oblige à annuler une réservation, vous êtes susceptible d'être éligible à un remboursement partiel ou intégral en cas de force majeur.</p>
      <p>      3.2 Modifications de réservation. Les Hôtes et les Voyageurs sont responsables de toute Modification de réservation qu'ils acceptent d'apporter par le biais de la plate-forme Atypikhouse ou demandent au service clients d’Atypikhouse d'effectuer en leur nom (« modifications de réservation »), et acceptent de payer tout montant, frais ou taxes supplémentaires associés à toute Modification de réservation.</p>
      <p>      4. Vos responsabilités.</p>
      <p>      Vous êtes responsable de vos propres actes et omissions et êtes également responsable des actes et omissions de toute personne que vous invitez à vous rejoindre (ou à qui vous fournissez un accès) concernant un Hébergement ou une Expérience. Par exemple, cela signifie : (i) que vous avez la responsabilité de laisser un Hébergement (et les biens personnels associés) dans l'état dans lequel vous l'avez trouvé à votre arrivée, et (ii) que vous devez agir avec intégrité, traiter les autres avec respect et vous conformer aux lois applicables en tout temps. Si vous réservez pour un Voyageur supplémentaire qui est mineur ou si vous faites venir un mineur dans un Service d'hôte, vous devez être légalement autorisé à agir au nom du mineur et vous êtes seul responsable de la supervision de ce mineur.</p>

      <h3>      Conditions relatives aux Hôtes</h3>
      <p>      5. Accueil de voyageurs avec Atypikhouse.</p>
      <p>      5.1 Hôte. En tant qu'hôte, Atypikhouse vous offre la possibilité de partager votre Hébergement, expérience ou autre Service d'hôte avec notre communauté de Voyageurs, et de gagner de l'argent ce faisant. Créer une Annonce est très facile. Vous contrôlez la façon dont vous accueillez les Voyageurs, et vous fixez votre prix, vos disponibilités et les règles pour chaque Annonce.</p>
      <p>      5.2 Contrat avec les Voyageurs. Lorsque vous acceptez une demande de réservation ou recevez une confirmation de réservation sur la plate-forme Atypikhouse, vous concluez un contrat directement avec le Voyageur et êtes responsable de la prestation du Service d'hôte selon les conditions et au prix spécifiés dans votre Annonce. Vous acceptez également de payer les frais applicables tels que les frais de services Atypikhouse (et les taxes applicables) pour chaque réservation. Atypikhouse déduira les montants dus de votre paiement, à moins que vous et nous ne convenions d'une autre méthode. Toutes les conditions ou modalités que vous incluez dans un contrat supplémentaire avec les Voyageurs doivent : (i) être conformes à ces conditions et aux informations fournies dans votre Annonce, et (ii) être divulguées de manière visible dans la description de votre Annonce.</p>
      <p>      5.3 Indépendance des Hôtes. Votre relation avec Atypikhouse est celle d'une entité ou d'un individu indépendant et non un salarié, agent, co-entrepreneur ou partenaire d'Atypikhouse, à l’exception du fait qu'Atypikhouse agit en tant qu'agent de recouvrement des paiements. Atypikhouse ne dirige ni ne contrôle votre Service d'hôte. Vous comprenez que vous avez toute latitude pour décider si et quand vous souhaitez fournir des Services d'hôte, et à quel prix et à quelles conditions les offrir.</p>
      <p>      6. Gestion de votre Annonce.</p>
      <p>      6.1 Création et gestion de votre Annonce. La plate-forme Atypikhouse fournit des outils qui vous permettent de configurer et de gérer facilement une Annonce. Votre Annonce doit inclure des informations complètes et précises sur votre Service d'hôte, votre prix, les autres frais éventuels tels que les frais de ménage, les frais de séjour, les cautions, et tous les règlements ou toutes les exigences qui s'appliquent à vos Voyageurs ou à votre Annonce. Vous êtes responsable de vos propres actes et omissions, ainsi que de la mise à jour et de l'exactitude des informations de votre annonce (y compris les dates de disponibilité de votre calendrier) et de son contenu (comme les photos) à tout moment. Nous vous recommandons de souscrire une assurance appropriée pour vos Services d'hôte, dont nous vous suggérons également de lire attentivement les conditions générales de la police, y compris les modalités de couverture et les exclusions.</p>
      <p>      6.2 Connaître ses obligations légales. Vous êtes tenu de comprendre et de respecter l'ensemble des lois, règlements, réglementations et contrats avec des tiers qui s'appliquent à votre Annonce ou vos Services d'hôte. Par exemple, certains propriétaires et baux, ou des règlements de copropriété, limitent ou interdisent la sous-location, les locations de courte durée et les séjours de longue durée. Certaines villes ont adopté des plans locaux d’urbanisme ou autres réglementations similaires qui restreignent la location de courte durée de propriétés résidentielles. Certaines collectivités locales, notamment des villes, exigent des Hôtes qu'ils s'enregistrent, obtiennent un permis ou un agrément avant de fournir certains Services d'hôte (tels que des locations de courte durée, des séjours de longue durée, la préparation de nourriture, la vente d'alcool, des visites guidées ou l'utilisation d'un véhicule). Dans certains endroits, les Services d'hôte que vous pourriez vouloir proposer peuvent être interdits. Certaines collectivités locales exigent l'enregistrement des Voyageurs qui séjournent dans votre Hébergement. Des juridictions ont adopté des réglementations qui créent des droits de location pour les Voyageurs et des obligations supplémentaires pour les Hôtes. Par exemple, certaines lois peuvent réglementer la location, le contrôle des loyers et l'expulsion pour les séjours de longue durée. Vérifiez la réglementation nationale et locale pour connaître les règles qui s'appliquent aux Services d'hôte que vous prévoyez d'offrir. Les informations que nous fournissons concernant les exigences légales sont uniquement à titre d'information. Vous devez vérifier vos obligations de manière indépendante. Vous êtes responsable du traitement et de l'utilisation des données personnelles des Voyageurs et d'autres personnes conformément aux lois sur la protection de la vie privée et aux présentes Conditions, y compris nos règles de confidentialité qui s'appliquent aux hôtes. Si vous avez des questions sur la façon dont la législation locale s'applique, vous devez toujours consulter un conseiller juridique tel un avocat.</p>
      <p>      6.3 Classement dans les résultats de recherche. Le classement des Annonces dans les résultats de recherche sur la plate-forme Atypikhouse dépend de plusieurs facteurs, principalement les suivants :</p>
      <p>      Paramètres de recherche indiqués par les Voyageurs (localisation)</p>
      <p>      Caractéristiques de l'Annonce (par exemple, prix, disponibilité du calendrier, nombre et qualité des images, commentaires, ancienneté de l'annonce, popularité moyenne des Voyageurs)</p>
      <p>      Expérience de réservation du Voyageur (par exemple, l'historique des annulations et du recours au service client de l'Hôte, la facilité de la réservation)</p>
      <p>      Exigences de l'Hôte (par exemple, nombre de nuits minimum ou maximum, heure limite de réservation)</p>
      <p>      6.4 Vos responsabilités. Vous êtes responsable de vos propres actes et omissions et êtes également responsable des actes et omissions de toute personne que vous autorisez à participer à la fourniture de vos Services d'hôte. Vous êtes responsable de la tarification et de l'établissement des règles et exigences de votre Annonce. Vous devez décrire tous les frais et redevances dans la description de votre Annonce, mais vous ne pouvez pas percevoir de frais ou redevances supplémentaires en dehors de la plate-forme Atypikhouse. N'encouragez pas les Voyageurs à créer des comptes tiers, à soumettre des commentaires, à fournir leurs coordonnées ou à prendre d'autres mesures en dehors de la plate-forme Atypikhouse.</p>
      <p>      6.5 Accueil de Voyageurs en tant qu'équipe ou organisation. Si vous travaillez avec un co-hôte ou un Hôte en tant que membre d'une équipe, d'une entreprise ou d'une autre organisation, l'entité et chaque individu qui participe à la fourniture des Services d'hôte sont responsables en tant qu'Hôte en vertu des présentes Conditions. Si vous acceptez des conditions ou si vous concluez des contrats, vous déclarez et garantissez que vous êtes autorisé à conclure des contrats pour votre équipe, votre entreprise ou toute autre organisation et que chaque entité que vous utilisez est en règle selon les lois du lieu où elle est établie. Si vous exercez d'autres fonctions, vous déclarez et garantissez être autorisé à exercer ces fonctions. Si vous demandez à Atypikhouse de transférer une partie de votre versement à un co-hôte ou à d'autres Hôtes, ou d'envoyer des paiements à un tiers, vous devez être autorisé à le faire. Vous êtes responsable des montants des paiements et de l'exactitude des informations que vous fournissez.</p>
      <p>      7. Annulations, problèmes de voyage et Modifications de réservation.</p>
      <p>      7.1 Annulations et problèmes de voyage. En général, si un Voyageur annule une réservation, le montant qui vous est payé est déterminé par les conditions d'annulation applicables à cette réservation. En tant qu'Hôte, vous ne devez pas annuler la réservation d'un Voyageur sans raison valable en vertu de la loi applicable. Si vous annulez la réservation d'un Voyageur sans une telle raison valable, nous pouvons imposer des frais d'annulation et d'autres conséquences. Si : (i) un Voyageur rencontre un problème de voyage, (ii) un cas de force majeure survient, ou (iii) une réservation est annulée en vertu de l'article 13 des présentes Conditions, le montant qui vous est payé est réduit du montant que nous remboursons ou fournissons au Voyageur, et de tous les autres frais raisonnables que nous encourons à la suite de l'annulation. Si un Voyageur reçoit un remboursement alors que vous avez déjà été payé, ou si le montant du remboursement et des autres frais engagés par Atypikhouse dépasse votre paiement, Atypikhouse (via Atypikhouse Payments) peut récupérer ce montant auprès de vous, y compris en déduisant le remboursement de vos versements futurs.</p>
      <p>      7.2 Modifications de réservation. Les Hôtes et les Voyageurs sont responsables de toute Modification de réservation qu'ils acceptent de faire sur la plate-forme Atypikhouse ou qu'ils demandent au service clients Atypikhouse de faire en leur nom, et acceptent de payer tout montant supplémentaire, frais ou taxes associés à une Modification de réservation.</p>
      <p>      8. Taxes.</p>
      <p>      8.1 Taxes des hôtes. En tant qu'Hôte, vous êtes responsable de déterminer et de remplir vos obligations en vertu des lois applicables pour déclarer, collecter, verser ou inclure dans votre prix toute TVA ou autres taxes indirectes, taxes de séjour, taxes de tourisme, impôts sur le revenu ou autres taxes applicables (« taxes »).</p>

      <h3>      Conditions d'application générale</h3>
      <p>      9. Évaluations.</p>
      <p>      Après chaque Service d'hôte, les Voyageurs et les Hôtes ont la possibilité de se laisser mutuellement un commentaire. Votre commentaire doit être précis et ne peut contenir aucun propos discriminatoire, offensant, diffamatoire. Les commentaires ne sont pas vérifiés par Atypikhouse et peuvent être infondés ou trompeurs.</p>
      <p>      12. Règles de la plate-forme Atypikhouse.</p>
      <p>      12.1 Règles. Vous devez respecter ces règles et ne devez pas aider ou inciter d'autres personnes à les enfreindre ou à les contourner.</p>
      <p>      Agir avec intégrité et traiter les autres avec respect</p>
      <p>      Ne pas mentir, représenter faussement quelque chose ou quelqu'un, ou prétendre être quelqu'un d'autre.</p>
      <p>      Faire preuve de politesse et de respect lorsque vous communiquez ou interagissez avec les autres.</p>
      <p>      Ne pas discriminer ou harceler les autres.</p>
      <p>      Ne pas endommager, pirater, faire de l'ingénierie inverse (reverse engineering), compromettre ou altérer la plate-forme Atypikhouse</p>
      <p>      Ne pas utiliser des robots, crawlers, scrapers ou autres moyens automatisés pour accéder à des données ou autre Contenu ou les récupérer sur la plate-forme Atypikhouse ou pour interagir avec cette dernière.</p>
      <p>      Ne pas pirater, contourner, supprimer, altérer ou tenter de circonvenir toute mesure de sécurité ou technologique utilisée pour protéger la plate-forme ou le contenu Atypikhouse.</p>
      <p>      Ne pas déchiffrer, décompiler, désassembler ou faire de l'ingénierie inverse des logiciels ou du matériel utilisés pour fournir la plate-forme Atypikhouse.</p>
      <p>      Ne pas entreprendre d'action qui pourrait perturber ou nuire à la performance ou au bon fonctionnement de la plate-forme Atypikhouse.</p>
      <p>      Ne pas utiliser la plate-forme Atypikhouse en dehors du cadre des présentes Conditions ou de tout autre contrat établi avec Atypikhouse</p>
      <p>      Vous ne pouvez utiliser les informations personnelles d'un autre Membre que dans la mesure du nécessaire pour faciliter une transaction utilisant la Plate-forme Atypikhouse, comme autorisé par les présentes Conditions.</p>
      <p>      Ne pas utiliser la plate-forme Atypikhouse, nos outils de messagerie ou les informations personnelles des Membres pour envoyer des messages commerciaux sans le consentement explicite du destinataire.</p>
      <p>      Utiliser le Contenu mis à disposition par la plate-forme Atypikhouse uniquement si cela est nécessaire pour vous permettre d'utiliser la plate-forme Atypikhouse en tant que Voyageur ou Hôte.</p>
      <p>      Ne pas utiliser le Contenu sauf si vous disposez de la permission du propriétaire du Contenu ou si l'utilisation est autorisée par nous dans ces conditions ou dans un autre contrat que vous avez établi avec Atypikhouse.</p>
      <p>      Ne pas demander, effectuer ou accepter une Réservation ou un Versement en dehors de la Plate-forme Atypikhouse pour éviter de payer des frais, des taxes ou pour toute autre raison.</p>
      <p>      Ne pas obliger ou encourager les Voyageurs à ouvrir un compte, laisser un commentaire ou interagir de toute autre manière avec un site web, une application ou un service tiers avant, pendant ou après une réservation, sauf autorisation d'Atypikhouse.</p>
      <p>      Ne pas tenter de manipuler notre algorithme de recherche.</p>
      <p>      Ne pas réserver de Services d'hôte à moins que vous n'utilisiez effectivement ces services.</p>
      <p>      Ne pas utiliser, copier, afficher ou encadrer la plate-forme Atypikhouse, tout Contenu, toute marque Atypikhouse, ou toute mise en page ou conception sans notre consentement.</p>
      <p>      Respecter vos obligations légales</p>
      <p>      Comprendre et respecter les lois qui s'appliquent à vous, y compris les lois sur la vie privée, la protection des données et l'exportation.</p>
      <p>      Si vous nous fournissez les informations personnelles relatives à une autre personne : (i) vous devez le faire dans le respect du droit applicable, (ii) vous devez être autorisé à le faire, et (iii) vous nous autorisez à traiter ces informations dans le cadre de notre Politique de confidentialité.</p>
      <p>      Ne pas organiser ou faciliter des fêtes ou des événements non autorisés. Vous êtes responsable de toute fête ou événement pendant votre réservation.</p>
      <p>      Ne pas utiliser le nom, le logo, la marque ou les marques déposées Atypikhouse ou d'autres personnes sans autorisation.</p>
      <p>      Ne pas utiliser ou enregistrer un nom de domaine, un identifiant de réseau social, un nom commercial, une marque, un logo ou tout autre identifiant de source qui pourrait être confondu avec la marque Atypikhouse.</p>
      <p>      Ne pas proposer de Services d'hôte qui enfreignent les lois ou les contrats qui vous concernent.</p>
      <p>      Ne pas offrir ou solliciter de services de prostitution, ni participer à la traite des êtres humains ou la faciliter.</p>
      <p>      12.2 Signalement d'une infraction.. Si vous pensez qu'un Membre, une Annonce ou un Contenu présente un risque imminent de dommage pour une personne ou un logement, vous devez immédiatement contacter les autorités locales avant de contacter Atypikhouse. En outre, si vous pensez qu'un Membre, une Annonce ou un Contenu constitue un manquement, vous devez faire part de vos préoccupations à Atypikhouse. Si vous avez signalé un problème aux autorités locales, Atypikhouse peut demander une copie de ce signalement. Sauf si la loi l'exige, nous ne sommes pas tenus de prendre des mesures en réponse à un signalement.</p>
      <p>      12.3 Notifications du droit d'auteur. Si vous pensez qu'un Contenu de la plate-forme Atypikhouse viole des droits d'auteur, veuillez nous en informer.</p>
      <p>      13. Résiliation, suspension et autres mesures.</p>
      <p>      13.1 Durée. Le contrat entre vous et Atypikhouse reflété par ces Conditions reste en vigueur jusqu'à ce que vous ou nous résilions le contrat conformément à ces Conditions.</p>
      <p>      13.2 Résiliation. Vous pouvez résilier le présent contrat à tout moment en nous envoyant un e-mail ou en supprimant votre compte. Atypikhouse peut résilier ce contrat pour toute raison en vous donnant un préavis de 30 jours par e-mail ou en utilisant toute autre coordonnée que vous avez fournie pour votre compte. Atypikhouse peut également résilier ce contrat immédiatement et sans préavis et cesser de fournir l'accès à la plate-forme Atypikhouse si (i) vous violez matériellement ces Conditions ou nos Politiques, si (ii) vous violez les lois applicables, ou si (iii) une telle action est nécessaire pour protéger la sécurité personnelle ou la propriété d'Atypikhouse, de ses Membres ou de tiers (par exemple, dans le cas d'un comportement frauduleux d'un Membre), ou si (iv) votre compte est inactif depuis plus de deux ans.</p>
      <p>      13.3 Infractions commises par un Membre. Si (i) vous violez ces Conditions, nos Politiques, si (ii) vous violez les lois applicables, les règlements ou les droits des tiers, si (iii) vous avez reçu à plusieurs reprises de mauvais commentaires ou si Atypikhouse prend connaissance ou a reçu des plaintes concernant votre performance ou votre conduite, si (iv) vous avez annulé à plusieurs reprises des réservations confirmées ou si vous n'avez pas répondu aux demandes de réservation sans raison valable, ou si (v) une telle action est nécessaire pour protéger la sécurité personnelle ou la propriété d'Atypikhouse, de ses Membres ou de tiers, Atypikhouse peut :</p>
      <p>     suspendre ou limiter votre accès à la plate-forme Atypikhouse et/ou à votre compte, ou son utilisation ;
        suspendre ou supprimer les Annonces, les commentaires ou tout autre Contenu ;
        annuler des réservations en cours ou confirmées ; ou
        suspendre ou révoquer tout statut spécial associé à votre compte.</p>
      <p>      En cas d'infractions mineures ou s'il y a lieu, vous serez informé de toute mesure envisagée par Atypikhouse et aurez la possibilité de remédier au problème, sauf si cette notification (i) éviterait ou empêcherait la détection ou la prévention de la fraude ou d'autres activités illégales en cause, (ii) porterait préjudice aux intérêts légitimes d'autres Membres ou de tiers, ou (iii) violerait les lois applicables.</p>
      <p>      13.4 Mandats légaux. Atypikhouse peut prendre toute mesure qu'il juge raisonnablement nécessaire pour se conformer à la loi applicable, ou à une décision d'un tribunal, ou de toute autre autorité judiciaire, administrative ou de police dûment habilitée, y compris les mesures décrites ci-dessus dans l'article 13.3.</p>
      <p>      13.5 Effet de la résiliation. Si vous êtes un Hôte et résiliez votre compte Atypikhouse, toutes les réservations confirmées seront automatiquement annulées et vos Voyageurs recevront un remboursement intégral. Si vous supprimez votre compte Atypikhouse en tant que Voyageur, toutes les réservations confirmées seront automatiquement annulées et le remboursement éventuel dépendra des conditions d'annulation de l'Annonce. En cas de résiliation de ce contrat, vous n'avez pas droit à une restauration de votre compte ou de votre Contenu. Si votre accès à la plate-forme Atypikhouse ou son utilisation a été limité, si votre compte Atypikhouse a été suspendu, ou ce contrat a été résilié par nous, vous ne pouvez pas enregistrer un nouveau compte ou accéder à la plate-forme ou l'utiliser Atypikhouse à travers un compte d'un autre Membre.</p>
      <p>      13.6 Appel. Si Atypikhouse prend l'une ou l'autre des décisions définies à l'article 13, vous pouvez faire appel de cette décision en contactant notre service clients.</p>
      <p>      14. Rôle d'Atypikhouse.</p>
      <p>      Nous offrons une plate-forme permettant aux Membres de publier, d'offrir, de rechercher et de réserver des Services d'hôte. Lorsque des Membres font ou acceptent une réservation, ils concluent un contrat entre eux directement. Atypikhouse n'est pas et ne devient pas partie à un quelconque contrat passé entre des Membres. Atypikhouse n'agit pas en qualité de mandataire d'un quelconque Membre, sauf lorsque Atypikhouse Payments agit en qualité de mandataire de recouvrement comme le prévoient les Conditions de paiement. Bien que nous fassions tout notre possible pour nous assurer que nos Membres vivent d'excellentes expériences avec Atypikhouse, nous ne contrôlons pas et ne pouvons pas contrôler la conduite des Voyageurs et des Hôtes et nous ne garantissons pas (i) l'existence, la qualité, la sécurité, la pertinence ou la légalité des Annonces ou des Services d'hôte ou (ii) la véracité ou l'exactitude des descriptions des Annonces, des commentaires ou d'autres Contenus fournis par les Membres. Vous reconnaissez qu'Atypikhouse n'a aucune obligation de surveiller l'utilisation de la plate-forme Atypikhouse et de vérifier les informations fournies par nos Membres, mais a le droit de vérifier le Contenu, désactiver son accès, le supprimer ou le modifier pour : (i) exploiter, sécuriser et améliorer la plate-forme Atypikhouse (y compris pour la prévention des fraudes, l'évaluation des risques, la conduite d’investigations ou encore le service clients) ; (ii) assurer la conformité des Membres aux présentes Conditions ; (iii) se conformer à la loi applicable ou à la décision d'un tribunal ou d’une autorité judiciaire, administrative ou policière dûment habilitée ; (iv) traiter le Contenu que nous déterminons comme étant nuisible ou répréhensible ; (v) prendre les mesures énoncées dans les présentes Conditions ; et (vi) maintenir et appliquer tout critère de qualité ou d'éligibilité, y compris en supprimant les Annonces qui ne répondent pas aux critères de qualité et d'éligibilité. Lorsque Atypikhouse supprime ou désactive du Contenu de Membres, Atypikhouse informe le Membre et lui donne les raisons de cette décision sauf si cette notification (i) empêche ou gêne la découverte d'une fraude ou d'une autre activité illégale, (ii) nuit à l'intérêt légitime des autres Membres ou de tiers, ou (ii) enfreint le droit applicable. Vous pouvez faire appel de cette décision en nous contactant directement. Les membres s'engagent à coopérer avec Atypikhouse et à l'aider en toute bonne foi à fournir à Atypikhouse les informations requises et à prendre les mesures raisonnables demandées par Atypikhouse, en lien avec toute enquête menée par Atypikhouse sur l'utilisation ou l'utilisation abusive de la plate-forme Atypikhouse.</p>
      <p>      17. Comptes membres.</p>
      <p>      Vous devez créer un compte pour accéder à de nombreuses fonctionnalités de la plate-forme Atypikhouse et les utiliser. L'inscription n'est autorisée que pour les personnes morales et les personnes physiques âgées de 18 ans ou plus. Vous déclarez et garantissez que vous n'êtes pas une personne ou une entité interdite d'utiliser la plate-forme Atypikhouse en vertu des lois des États-Unis, de votre adresse de résidence ou de toute autre juridiction pertinente. Vous devez fournir des informations exactes et complètes lors de l'inscription, et tenir à jour les informations relatives à votre compte. Vous ne pouvez pas créer plus d'un compte ou transférer votre compte à quelqu'un d'autre. Il vous appartient de préserver la confidentialité et la sécurité de vos identifiants de compte, et il vous est interdit de divulguer vos identifiants à un quelconque tiers. Vous devez immédiatement informer Atypikhouse si vous suspectez que vos identifiants ont été perdus, volés, ou que votre compte est autrement compromis. Vous êtes responsable de toutes les activités menées avec votre compte Atypikhouse, sauf si vous n’avez pas autorisé ces activités et que vous n’avez pas fait preuve de négligence par ailleurs (par exemple, en ne signalant pas l'utilisation non autorisée ou la perte de vos identifiants). Si la loi applicable le permet, nous pouvons, mais n'avons aucune obligation de (i) vous demander de fournir une pièce d'identité ou d'autres informations, (ii) entreprendre des vérifications destinées à aider à contrôler votre identité ou vos antécédents, (iii) vous comparer à des bases de données de tiers ou à d'autres sources et demander des rapports à des prestataires de services, et (iv) obtenir des rapports des registres publics des condamnations pénales ou des fichiers de délinquants sexuels ou de leurs équivalents locaux.</p>
      <p>      18. Exclusion de responsabilité.</p>
      <p>      Nous n'endossons pas ou ne garantissons pas l'existence, la conduite, la performance, la sécurité, la qualité, la légalité ou l'adéquation de tout Voyageur, Hôte, Service Hôte, Annonce ou tiers. La vérification des utilisateurs sur Internet est difficile, et nous ne garantissons pas que les vérifications, les contrôles d'identité ou d'antécédents effectués sur les Membres (le cas échéant) permettront d'identifier les manquements passés ou d'en prévenir de futurs. Toutes les références à un Membre « vérifié » (ou tout terme similaire) signifient uniquement que le Membre a fait l'objet d'une procédure de vérification ou d'identification appropriée, et rien d'autre. Nous ne sommes pas responsables en cas de pannes ou coupures d'Internet ou des infrastructures de télécommunications qui ne relèvent pas de notre contrôle et qui peuvent conduire à des interruptions de l'accessibilité de la plate-forme Atypikhouse. Atypikhouse peut, de façon temporaire et en prenant en compte les intérêts légitimes des Membres (par exemple par une notification préalable), limiter la disponibilité de la plate-forme Atypikhouse ou de certaines fonctionnalités de la plate-forme Atypikhouse si cela est nécessaire en raison de capacités limitées, pour préserver la sécurité ou l'intégrité de nos serveurs, ou pour effectuer des opérations de maintenance afin d'assurer le bon fonctionnement ou d'améliorer le fonctionnement de la plate-forme Atypikhouse.</p>
      <p>      19. Responsabilité.</p>
      <p>      Atypikhouse peut être tenu responsable en vertu des dispositions légales applicables en cas de faute intentionnelle et grave commise par nous, nos représentants légaux, administrateurs ou mandataires. Il en va de même pour la prise en charge des garanties ou de toute autre responsabilité stricte ou en cas d'atteinte à la vie, à l'intégrité physique ou à la santé. En cas de manquements à des obligations contractuelles commis par nous, nos représentants légaux, administrateurs ou mandataires, la responsabilité d'Atypikhouse est limitée aux dommages prévisibles typiques pouvant survenir.</p>
      <p>      20. Indemnisation.</p>
      <p>      Dans la mesure maximale permise par la loi applicable, vous acceptez de libérer, défendre (au choix d'Atypikhouse), indemniser et tenir Atypikhouse (y compris Atypikhouse Payments, d'autres filiales et leur personnel) à l'abri de l'ensemble des réclamations, responsabilités, dommages, pertes et dépenses découlant de ou en relation avec : (i) votre violation de ces Conditions (y compris toute condition supplémentaire ou additionnelle qui s'applique à un produit ou une fonctionnalité et qui vous serait présentée avant que vous y accédiez), (ii) votre utilisation inappropriée de la plate-forme Atypikhouse, (iii) votre interaction avec tout Membre, séjour dans un logement, participation à une Expérience ou autre Service d'hôte, y compris, mais sans s'y limiter, tout préjudice, perte ou dommage (compensatoire, direct, accessoire, immatériel ou autre) de toute sorte survenant en relation avec ou à la suite d'une Annonce, d'un séjour, d'une participation ou d'une utilisation de ce type, (iv) votre manquement, ou notre manquement à vos instructions, à déclarer, collecter ou remettre avec précision les taxes, ou (v) votre violation de toute loi ou de tout règlement ou droit de tiers tels que les droits de propriété intellectuelle ou de confidentialité. La présente obligation d'indemnisation ne s'applique que si, et dans la mesure où, les réclamations, responsabilités, dommages, pertes et dépenses ont été effectivement causés par votre manquement fautif à une obligation contractuelle.</p>
      <p>      21. Entités Atypikhouse contractantes.</p>
      <p>      En fonction de votre pays de résidence ou d'établissement et de votre activité sur la Plateforme Atypikhouse, l'annexe 1 ci-dessous indique l'entité juridique d'Atypikhouse avec laquelle vous concluez un contrat. Si nous identifions par le biais de la plate-forme Atypikhouse qu'une entité Atypikhouse autre que celle figurant sur l'annexe 1 est responsable d'un produit, d'une fonctionnalité ou d'une transaction, l'entité Atypikhouse ainsi identifiée est votre entité contractante en ce qui concerne ce produit, cette fonctionnalité ou cette transaction. Si vous changez de pays de résidence ou d'établissement pour un pays en dehors de l'EEE, de la Suisse ou du Royaume-Uni, l’entité Atypikhouse avec laquelle vous concluez un contrat et la version applicable de ces Conditions seront déterminées par votre nouveau pays de résidence ou d'établissement, à partir de la date à laquelle votre pays de résidence ou d'établissement change.</p>
      <p>      22. Droit applicable et juridiction compétente.</p>
      <p>      Les présentes Conditions sont régies et interprétées conformément au droit irlandais. Si vous agissez en tant que consommateur et si la réglementation légale impérative de protection des consommateurs de votre pays de résidence contient des dispositions qui sont plus avantageuses pour vous, ces dispositions s'appliquent indépendamment du choix du droit irlandais. En tant que consommateur, vous pouvez engager toute poursuite judiciaire relative aux présentes Conditions devant le tribunal compétent de votre lieu de résidence ou le tribunal compétent du lieu d'établissement d'Atypikhouse en Irlande. Si Atypikhouse souhaite faire valoir ses droits à votre encontre en tant que consommateur, nous ne pourrons le faire que dans les tribunaux de la juridiction dont vous dépendez. Si vous agissez en tant que professionnel, vous acceptez de vous soumettre à la compétence exclusive des tribunaux irlandais.</p>
      <p>      À quoi correspondent les frais de service Atypikhouse ?</p>
      <p>      Afin de contribuer au bon fonctionnement d’Atypikhouse, et de couvrir les coûts des produits et services que nous fournissons, comme l'assistance utilisateurs 24h/24, nous facturons des frais de service lorsqu'une réservation est confirmée.</p>
      <p>      Frais de réservation d'un hébergement</p>
      <p>      Des frais de service sont déduits du versement à l'hôte et des frais de service sont facturés aux voyageurs.</p>


      <h3>Comment fonctionnent les taxes pour les voyageurs ?</h3>
      <p>      Dans certains cas, les voyageurs Atypikhouse peuvent être amenés à payer une taxe.
        Certains hôtes doivent appliquer une taxe pour se conformer à leur législation locale. Nous recommandons aux hôtes d'inclure la taxe dans le prix de la réservation, mais certains peuvent exiger le paiement de la taxe directement à l'arrivée. Nous demandons aux hôtes de préciser dans la description de leur logement ou dans leurs échanges avec les voyageurs avant la réservation s'ils appliquent une taxe supplémentaire sur leurs tarifs.
        Par ailleurs, Atypikhouse est tenu de collecter la TVA ou son équivalent (comme la taxe sur la consommation japonaise) sur ses frais de service dans les pays appliquant une taxe sur les services fournis par voie électronique. Actuellement, cela comprend tous les pays de l'UE, l'Afrique du Sud, l'Albanie, l'Arabie saoudite, les Bahamas, le Chili, la Colombie, l'Islande, le Japon, le Mexique, la Norvège, la Suisse et l'Uruguay.
        Atypikhouse est également tenu de collecter la TVA sur ses frais de service pour les utilisateurs ayant un contrat avec Atypikhouse Chine.
      </p>

      <h3>Règles en matière de confidentialité pour les hôtes</h3>
      <p>      Traitement des informations personnelles du Voyageur
        En tant qu'Hôte, vous recevrez et utiliserez les informations personnelles des Voyageurs pour gérer vos réservations et fournir votre Service d'Hôte. N'oubliez pas qu'il relève de votre responsabilité de respecter les lois sur la protection des données lorsque vous traitez des informations personnelles. Vous ne devez utiliser les informations personnelles que vous recevez par le biais de la Plateforme Atypikhouse uniquement dans la mesure nécessaire à la gestion de vos réservations et pour fournir votre Service d'Hôte. Vous n'avez pas le droit d'encourager ou d'obliger les Voyageurs à : ouvrir un compte, laisser un commentaire ou interagir de toute autre manière que ce soit avec un site web, une application ou un service tiers avant, pendant ou après une réservation, sauf sur autorisation d'Atypikhouse.
      </p>
      <h3>Transferts transfrontaliers</h3>
      <p>
        Si, dans le cadre de la fourniture de Services d'Hôte, (i) vous recevez des informations personnelles en provenance de l'Espace Economique Européen, de la Suisse ou du Royaume-Uni (conformément à l'article 44 du Règlement général sur la protection des données « RGPD ») et (ii) ce transfert ne bénéficie pas d'une décision d'adéquation en vertu de l'article 45 du RGPD, vous acceptez alors de traiter les informations personnelles que vous recevez conformément aux principes énoncés dans l'Annexe A des clauses contractuelles types (« Clauses ») figurant dans la décision 2004/915/CE de la Commission Européenne. En vertu du présent document, les Clauses sont incorporées dans le contrat que vous avez signé avec nous.</p>
      <h3>      Clauses contractuelles types</h3>
      <p>      Les informations nécessaires pour compléter les Clauses sont les suivantes :</p>
      <p>      Vous êtes « l'importateur de données ».
        Si vous êtes Hôte ou réservez une annonce au Japon, « l'exportateur de données » est Atypikhouse Global Services Limited.
        Si vous êtes Hôte ailleurs qu'au Japon, « l'exportateur de données » est Atypikhouse Ireland UC.
      </p>
      <h3>
        Concernant l'Annexe B des Clauses :</h3>
      <p>(i) les personnes concernées sont les Voyageurs ;</p>
      <p>      (ii) l'objet du transfert est de vous permettre de fournir le Service d'Hôte ;</p>
      <p>      (iii) les catégories de données peuvent inclure le profil et le nom complet du Voyageur, le nom complet de tout Voyageur supplémentaire (si saisi), l'historique des annulations du Voyageur, le numéro de téléphone du Voyageur, toute autre information que le Voyageur choisira de transmettre, et d'autres informations permettant de mieux coordonner le voyage, y compris les messages échangés avec le Voyageur ;</p>
      <p>      (iv) les destinataires des données sont tous les prestataires de services que vous pouvez choisir de retenir pour vous aider à fournir les Services d'Hôte ;</p>
      <p>      (v) aucune donnée sensible n'est transférée ;</p>
      <p>      (vi) il n'existe aucune information d'enregistrement pertinente quant à la protection des données à moins que vous nous en avisiez autrement ; et</p>
      <p>      (vii) pour les demandes relatives à la protection des données, vous pouvez contacter notre délégué à la protection des données, ici à la section « Nous contacter », et nous pouvons vous contacter par e-mail à l'adresse figurant sur votre profil.</p>


    </Stack>
  )
}

export default CGS;

